site_name: AAS Security Labs Docs
site_url: https://abdelwahab-a-shendy.github.io/SecLab-Hub/

theme:
  name: material
  language: en
  palette:
    
    - scheme: slate
      primary: black
      accent: blue
  features:
    - navigation.tabs
    - navigation.sections
    - search.share

docs_dir: 'SecLab-Notes'
site_dir: 'SecLab-Hub'


extra_css:
  - extra.css
